name: With Artifact

on:
  workflow_dispatch:

jobs:
  artifact:
    name: Upload random data
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact
        run: head -c 1M </dev/urandom > artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ github.ref_name }}
          path: artifact
